### ISSUE TITLE
Which Spaced Repetition Algorithm?

### ISSUE THREAD

**Issue by Positron010** [harmancode/Flashcards#1]
Hello,

Could you please state which spaced repetition algorithm this app uses?

Thanks!

**Comment by harmancode** [comment]
Hello,

This program uses SM-2 Algorithm. Explained here: https://en.wikipedia.org/wiki/SuperMemo#Description_of_SM-2_algorithm

Thanks!

**Comment by Positron010** [comment]
Thanks for replying!
